### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by hayeong0** [kehanlu/DeSTA2#2]
Thank you for sharing your nice work! 
The approach of extracting and leveraging speech features to naturally learn the connection between speech and text is truly interesting. 
I tested it on English and Korean, and it works successfully. 

Just a very minor detail: `from huggingface import AutoModel` -> `from transformers import AutoModel`

Thanks.

**Comment by kehanlu** [comment]
Hello @hayeong0,
Thank you for your positive feedback! I am glad you are interested in our work.
We have fixed the typo, thank you again. :smile:
